default: &default
  adapter: postgresql
  host: <%= ENV.fetch('DATABASE_HOST') { "localhost" }%>
  port: <%= ENV['DATABASE_PORT'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: <%= ENV.fetch('DATABASE_TIMEOUT') { 5000 } %>

development:
  <<: *default
  database: flash_cards_dev

test:
  <<: *default
  database: flash_cards_test

production:
  <<: *default
  database: flash_cards_prod
